version: '3.3'
services:
    hasura:
      depends_on:
        - db
      # command:
      #   - "hasura metadata track --all-tables [--schema public]"
      ports:
          - '0.0.0.0:8080:8080'
      environment:
          - 'HASURA_GRAPHQL_DATABASE_URL=postgres://indexer:qwerty@hb-indexer-postgres:5432/indexer_db'
          - HASURA_GRAPHQL_ENABLE_CONSOLE=true
          - HASURA_GRAPHQL_DEV_MODE=true
          - HASURA_GRAPHQL_ADMIN_SECRET=changeme
          - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=indexer
          - HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
      image: hasura/graphql-engine:v2.8.3.cli-migrations-v3
      restart: always
    db:
      container_name: hb-indexer-postgres
      ports:
          - '0.0.0.0:5432:5432'
      environment:
          - POSTGRES_USER=indexer
          - POSTGRES_PASSWORD=qwerty
          - POSTGRES_DB=indexer_db
      image: postgres
    indexer:
      build: .
      depends_on:
        - db
      command: ["-c", "dipdup.yml", "run"]
      environment:
        - PG_HOST=db
        - PG_PORT=5432
        - PG_USER=indexer
        - PG_PASSWORD=qwerty
        - PG_DB=indexer_db
        - PG_SCHEMA=public
      ports:
        - 0.0.0.0:9000:9000