# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class FreezeHistory(BaseModel):
    current_stage_num: str
    current_unstaked: str
    past_unstaked: str
    staked: str


class GovernanceToken(BaseModel):
    address: str
    token_id: str


class Key(BaseModel):
    address: str
    nat: str


class LedgerItem(BaseModel):
    key: Key
    value: str


class Key1(BaseModel):
    operator: str
    owner: str
    token_id: str


class Operator(BaseModel):
    key: Key1
    value: Dict[str, Any]


class ProposalKeyListSortByDateItem(BaseModel):
    bytes: str
    timestamp: str


class Voter(BaseModel):
    vote_amount: str
    vote_type: bool
    voter_address: str


class Proposals(BaseModel):
    downvotes: str
    metadata: str
    proposer: str
    proposer_frozen_token: str
    quorum_threshold: str
    start_date: str
    upvotes: str
    voters: List[Voter]
    voting_stage_num: str


class QuorumThresholdAtCycle(BaseModel):
    last_updated_cycle: str
    quorum_threshold: str
    staked: str


class RegistryStorage(BaseModel):
    admin: str
    custom_entrypoints: Dict[str, str]
    decision_lambda: str
    extra: Dict[str, str]
    fixed_proposal_fee_in_token: str
    freeze_history: Dict[str, FreezeHistory]
    frozen_token_id: str
    governance_token: GovernanceToken
    governance_total_supply: str
    guardian: str
    ledger: List[LedgerItem]
    max_proposals: str
    max_quorum_change: str
    max_quorum_threshold: str
    max_votes: str
    metadata: Dict[str, str]
    min_quorum_threshold: str
    operators: List[Operator]
    pending_owner: str
    period: str
    permits_counter: str
    proposal_check: str
    proposal_expired_time: str
    proposal_flush_time: str
    proposal_key_list_sort_by_date: List[ProposalKeyListSortByDateItem]
    proposals: Dict[str, Proposals]
    quorum_change: str
    quorum_threshold_at_cycle: QuorumThresholdAtCycle
    rejected_proposal_return_value: str
    start_time: str
    total_supply: Dict[str, str]
