# generated by datamodel-codegen:
#   filename:  callCustom.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CallCustomParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    string: str
    bytes: str
