# generated by datamodel-codegen:
#   filename:  unstake_vote.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class UnstakeVoteParameter(BaseModel):
    __root__: List[str]
