# generated by datamodel-codegen:
#   filename:  vote.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Argument(BaseModel):
    proposal_key: str
    vote_type: bool
    vote_amount: str


class PermitItem(BaseModel):
    key: str
    signature: str


class VoteParameterItem(BaseModel):
    argument: Argument
    permit: Optional[PermitItem]


class VoteParameter(BaseModel):
    __root__: List[VoteParameterItem]
