name: Heroku Docker Deployment.
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache --build-arg PG_HOST=${{ secrets.PG_HOST }} --build-arg PG_PORT=${{ secrets.PG_PORT }} --build-arg PG_USER=${{ secrets.PG_USER }} --build-arg PG_PASSWORD=${{ secrets.PG_PASSWORD }} --build-arg PG_DB=${{ secrets.PG_DB }} --build-arg PG_SCHEMA=${{ secrets.PG_SCHEMA }}"
          process_type: web